#!/bin/bash
# RAY.sh - self-contained LOVE port. Generated by deploy-usb.ps1.
# Expects, inside the port folder:
#   love          (aarch64 binary, e.g. Cebion/love2d_aarch64)
#   libs/         (liblove.so.0 and friends)
#   game.love
#
# PortMaster is used when present, but is NOT required: without it the
# script falls back to sane ArkOS defaults instead of dying on a missing
# control.txt.

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

controlfolder=""
for d in "/opt/system/Tools/PortMaster" "/opt/tools/PortMaster" \
         "$XDG_DATA_HOME/PortMaster" "/roms/ports/PortMaster"; do
  [ -d "$d" ] && { controlfolder="$d"; break; }
done

if [ -n "$controlfolder" ] && [ -f "$controlfolder/control.txt" ]; then
  source "$controlfolder/control.txt"
  [ -f "$controlfolder/mod_${CFW_NAME}.txt" ] && source "$controlfolder/mod_${CFW_NAME}.txt"
  command -v get_controls >/dev/null 2>&1 && get_controls
fi

# fallbacks if PortMaster did not define these
[ -z "$directory" ] && directory="roms"
if [ -z "$ESUDO" ]; then
  if [ "$(id -u)" -eq 0 ]; then ESUDO=""; else ESUDO="sudo"; fi
fi
command -v $ESUDO >/dev/null 2>&1 || ESUDO=""

GAMEDIR="/$directory/ports/RAY"
# second card / alternate mount, if the port is not where we guessed
if [ ! -d "$GAMEDIR" ]; then
  for alt in /roms/ports/RAY/roms2/ports/RAY\
             /mnt/mmc/roms/ports/RAY/mnt/sdcard/roms/ports/RAY; do
    [ -d "$alt" ] && { GAMEDIR="$alt"; break; }
  done
fi

cd "$GAMEDIR" || exit 1

> "$GAMEDIR/log.txt" && exec > >(tee "$GAMEDIR/log.txt") 2>&1

echo "--- gamedir: $GAMEDIR"
ls -la "$GAMEDIR"

# Bundled engine, no runtime mounting
export LD_LIBRARY_PATH="$GAMEDIR/libs:$LD_LIBRARY_PATH"
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"

# Some aarch64 LOVE builds need this to select the GLES backend
export LOVE_GRAPHICS_USE_OPENGLES=1

$ESUDO chmod +x "$GAMEDIR/love" 2>/dev/null
$ESUDO chmod 666 /dev/uinput 2>/dev/null

if [ ! -x "$GAMEDIR/love" ]; then
  echo "!!! $GAMEDIR/love is missing or not executable."
  echo "!!! Copy an aarch64 love binary and its libs/ into the port folder."
  sleep 5
  exit 1
fi

echo "--- launching love"
"$GAMEDIR/love" "$GAMEDIR/game.love"
echo "--- love exited with code $?"

printf "\033c" > /dev/tty0
